language: python
python: "3.5"
dist: xenial
env:
  - TOXENV=unittest
  - TEST=create ROS_DISTRO=kinetic TOXENV=py35-pypi
  - TEST=create ROS_DISTRO=kinetic TOXENV=py35-github
  - TEST=create ROS_DISTRO=melodic TOXENV=py35-pypi
  - TEST=create ROS_DISTRO=melodic TOXENV=py35-github
  - TEST=backwards ROS_DISTRO=kinetic TOXENV=py35-pypi
services:
  - docker
sudo: true
before_install:
  - sudo apt update && sudo apt install -y enchant
install:
  - pip install tox-travis
script:
  - tox
notifications:
  email: false
